name: cppcheck-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get_cppcheck
      run: sudo apt-get install cppcheck
    - name: cppcheck code
      run: cppcheck 3_Implementation
